Barzan's website/controllers/login.py
from flask import *
import extensions

url_prefix = extensions.url_prefix_String()
login = Blueprint('login', __name__, template_folder='templates',url_prefix=url_prefix)

@login.route('/login', methods= ["GET","POST"])
def login_route():
	if request.method == "GET":
		return render_template("login.html")

	db = extensions.connect_to_database()
	cur = db.cursor()
	fields = ['username', 'password']
	errList = []
	username = request.form['username'].lower()
	extensions.CheckField(errList,fields, request.form)

	query = "SELECT * FROM User WHERE username = %s"
	cur.execute(query,[request.form['username']])
	result = cur.fetchone()

	password = None

	if result is None:
		errList.append('Username does not exist')
	else:
		password = result['password']
		if not extensions.PasswordCheck(request.form['password'], password):
			errList.append('Password is inocorrect for the specified username')

	if errList == []:
		session['username'] = username
		session['firstname'] = result['firstname']
		session['lastname'] = result['lastname']
		return redirect(url_for('main.main_route'))

	return render_template('login.html', errList=errList)

Barzan's website/controllers/logout.py
from flask import *
import extensions

url_prefix = extensions.url_prefix_String()
logout = Blueprint('logout', __name__, template_folder='templates', url_prefix=url_prefix)

@logout.route('/logout', methods=["POST"])
def logout_route():
	if 'username' in session:
		session.clear()
	return redirect(url_for('main.main_route'))

Barzan's website/controllers/project_edit.py
from flask import *
import extensions
import os
import hashlib

url_prefix = extensions.url_prefix_String()
project_edit = Blueprint('project_edit', __name__, template_folder='templates',url_prefix=url_prefix)

@project_edit.errorhandler(404)
def page_not_found(e):
	return render_template('404.html'), 404

imagePath = os.path.join(os.path.abspath('.'), 'static', 'images')

@project_edit.route('/edit', methods= ['GET', 'POST'])
def project_edit_route():
	db = extensions.connect_to_database()
	cur = db.cursor()
	errList = []
	if 'username' not in session:
		return render_template('error2.html'), 403
	if request.method == 'POST':
		if not check_project_name(cur, request.form['project_name'].replace("'", "\'")):
			errList.append('Project name exists')
		else:
			file = request.files['file']
			if not file:
				query = 'INSERT INTO Projects VALUES(NULL, %s, %s, %s, %s, NULL, %s)'
				cur.execute(query, [request.form['project_name'], request.form['project_subtitle'], request.form['project_contents'], request.form['project_website'], request.form['status']])
				return redirect(url_for('main.main_route'))
			if file and allowed_file(file.filename):
				file_format = os.path.splitext(str(file.filename))[1]
				filename = getHash(file.filename)
				file.save(os.path.join(imagePath, filename + file_format))
				query = 'INSERT INTO Projects VALUES(NULL,%s,%s,%s,%s,%s,%s)'
				cur.execute(query,[request.form['project_name'], request.form['project_subtitle'], request.form['project_contents'], request.form['project_website'], filename + file_format ,request.form['status']])
				return redirect(url_for('main.main_route'))
			else:
				errList.append("Wrong file type! type can only be one of 'jpg', 'gif', 'png', 'bmp'")
	return render_template('project_edit.html', errList = errList)





def check_project_name(cur,project_name):
	query = 'SELECT * FROM Projects WHERE pname = %s'
	cur.execute(query, [project_name])
	result = cur.fetchone()
	return result is None

def allowed_file(filename):
	return '.' in filename and os.path.splitext(str(filename))[1] in ['.jpg', '.gif', '.png', '.bmp']

def getHash(filename):
    m = hashlib.md5(filename)
    return m.hexdigest()

Barzan's website/controllers/user.py
from flask import *
import extensions

url_prefix = extensions.url_prefix_String()
user = Blueprint('user', __name__, template_folder='templates',url_prefix=url_prefix)

@user.route('/user/edit', methods= ["GET","POST"])
def user_edit_route():
	if request.method == "GET" and not "username" in session:
		return redirect(url_for('login.login_route'))

	if request.method == "GET":
		return render_template('user_edit.html')

	db = extensions.connect_to_database()
	cur = db.cursor()
	errList = []
	fields = ['firstname', 'lastname', 'password1']
	username = escape(session['username'])

	if 'lastname' in request.form:
		if len(request.form['lastname']) > 20:
			errList.append("Lastname must be no longer than 20 characters")
			return render_template("user_edit.html", errList = errList)
		else:
			query = "UPDATE User SET lastname = %s WHERE username = %s"
			cur.execute(query, [request.form['lastname'], username])
			session['lastname'] = request.form['lastname']

	if 'firstname' in request.form:
		if len(request.form['firstname']) > 20:
			errList.append("Firstname must be no longer than 20 characters")
			return render_template("user_edit.html", errList = errList)
		else:
			query = "UPDATE User SET firstname = %s WHERE username = %s"
			cur.execute(query, [request.form['firstname'], username])
			session['firstname'] = request.form['firstname']

	if 'password1' in request.form:
		if (request.form['password1']) != (request.form['password2']):
			errList.append("Passwords do not match")
		extensions.password_valid(errList,request.form['password1'])
		if errList != []:
			return render_template("user_edit.html", errList = errList)
		else:
			query = "UPDATE User SET password = %s WHERE username = %s"
			cur.execute(query, [extensions.encrypt(request.form["password1"]), username])

	return render_template("user_edit.html", errList = errList)




		

Barzan's website/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
	<link rel="stylesheet" href="/static/css/style.css" />
	<style>
		
	    a:link, a:visited {
		    color: #7D0612;
		    text-decoration: none;
	    }

		a:hover, a:active{
			text-decoration: underline;
		}

	    #msbnav > div > div > a, #msbnav > div > div > span {
		    font-size: 32px;
		    font-family: "Lato",'Helvetica Neue',Helvetica,Arial,sans-serif;
		    color: #DCDCDC;
	    }
	    input:{
	    	width:600;
	    }
	
	</style>
</head>
<body>

<div class = "center">
    <p style="font-family:courier;">
		{% if session.username %} Welcome! {{session.firstname}} {{session.lastname}} ^v^
	<a href="{{ url_for('user.user_edit_route')}}" id="nav_edit"> Edit Account</a>
	<form action="{{ url_for('logout.logout_route')}}" method="post">
		<input type="submit" value="logout" id="nav_logout">
	</form>
	</p>
	
	{% endif %}
	{% if not session.username %} Hello visitor, you are currently not login.
	<a href="{{ url_for('login.login_route')}}", id="home_login"> Login</a>
	{% endif %}
	</div>
    <div style="font-size:180%;background-color: gold" align="center">
		<div class="navbar-header" > 
			<a class="navbar-brand" href="http://web.eecs.umich.edu/~mozafari/">Barzan Mozafari</a>
		</div> 
		<div class="navbar-header">
			<span class="navbar-brand" style="padding-left:0; padding-right:0">&nbsp;</span>
		</div>
		<div class="navbar-header"> 
			<a class="navbar-brand" href="http://umich.edu/">University Of Michigan</a>
		</div> 
		<div class="navbar-header">
			<span class="navbar-brand" style="padding-left:0; padding-right:0">&nbsp;</span>
		</div>
		<div class="navbar-header" > 
			<a class="navbar-brand" href="http://www.eecs.umich.edu/db/">Database Systems</a>
		</div>
	</div>
		{% block content %}{% endblock %}
<!-- </div> -->
	<script type="text/javascript" src="/static/js/main.js"></script>
</body>

</html>

Barzan's website/templates/error.html
{% extends "base.html" %} {% block content %}

<head>
  <title>Page Not Found</title>
  <meta charset="UTF-8">
  <meta name="description" content="EECS485 P1 404 page">
</head>

<header>

</header>

<body>
  <h1 style="text-align: center;"><pre>                                   
                                   
    .---.     .----.       .---.   
   / .  |    /  ..  \     / .  |   
  / /|  |   .  /  \  .   / /|  |   
 / / |  |_  |  |  '  |  / / |  |_  
/  '-'    | '  \  /  ' /  '-'    | 
`----|  |-'  \  `'  /  `----|  |-' 
     `--'     `---''        `--'   
     </pre></h1>
  <br>
  <p style="text-align: center;"><em>Page not found...</em></p>
</body>

{% endblock %}

Barzan's website/templates/error2.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">

<head>
  <title>Page Not Found</title>
  <meta charset="UTF-8">
  <meta name="description" content="EECS485 P1 404 page">
</head>

<header>

</header>

<body>
  <h1 style= "text-align: center; font-family:courier; font-size: 300% "><pre>    
403!!                    
     </pre></h1>
  <br>
  <p style="text-align: center;"><em>Page not found...</em></p>
</body>

</html>

Barzan's website/templates/index.html
{% extends "base.html" %}
{% block content %}
<html>
<head>
	<title>
		BARZAN MOZAFARI's website
	</title>
	<meta charset="UTF-8">
	<meta name = "description" content="BARZAN MOZAFARI's website">
</head>

<body>
	<h1>Current Projects</h1>
	<ul>
	{% for pj in curr %}
	    <li>
            <a href="#{{pj.pname}}">
                <b>{{pj.pname}}</b>
                {% if pj.subtitle %}
                 : {{pj.subtitle}}
                {% endif %}
            </a>
	    </li>
	{% endfor %}
	</ul>

    <h1>Past Projects</h1>
	<ul>
	{% for pj in past %}
	    <li>
            <a href="#{{pj.pname}}">
                <b>{{pj.pname}}</b>
                {% if pj.subtitle %}
                 : {{pj.subtitle}}
                {% endif %}
            </a>
	    </li>
	{% endfor %}
	</ul>
    {% if session.username %}
    <div class="strong" style="font-size:200%; background-color: lightblue" align="center" ;>
        <a href="{{url_for('project_edit.project_edit_route')}}"> Add new project</a>
    </div>
        <br>
        <br>
    {% endif %}
        {% for result in res.values() %}
        {% if session.username %}
        <div class ="delete_project" align="right">
        <form method="post" enctype="mulitpart/form-data" >
        <input type="hidden" name="op_project" value="delete">
        <input type="hidden" name="pid" value="{{result.project.pid}}">
        <input type = submit value="Delete Project: {{result.project.pname}}" style="font-size: 130%">
        </form>
        </div>
        {% endif %}
    <h2>
        <p style="line-height: 200%; margin-bottom: 0;">
                        <a name="{{result.project.pname}}"></a>
        <b><font size="6" face="Arial"><a href="#{{result.project.pname}}">
            {{result.project.pname}}</a>
                            </font></b>
        </p>
        {% if result.project.subtitle %}
        <font size="3" face="Arial"><a href="#{{result.project.pname}}">
            {{result.project.subtitle}}</a>
                            </font>
        {% endif %}
    </h2>
    {% if session.username %}
    <button onclick="myFunction('edit_title{{result.project.pid}}')"> Edit title </button>
    <form id = "edit_title{{result.project.pid}}" style="display: none" method="post" enctype="mulitpart/form-data">
        Please enter your new title: <input size="80" type=text name=title> <br>
        Please enter your new subtitle: <input size="80" type=text name=subtitle> <br>
        <input type="hidden" name=pid value = "{{result.project.pid}}"> <br>       
        <input type="submit" value="Submit">
    </form>
    {% endif %}
    <p>
        {% if result.project.pjwebsite %}
        <b><font size="3" face="Arial">Website: </font><a href="{{result.project.pjwebsite}}">{{result.project.pjwebsite}}</a></b>                
        {% endif %}

    </p>
        {% if result.peoples %}
        <p>

            <b><font size="3" face="Arial">People: </font></b>
            {% for people in result.peoples %}
            {% if people.pwebsite %}
            <a href ="{{people.pwebsite}}">{{people.name}}</a>, &nbsp
            {% else %}
            {{people.name}}
            {% endif %}
<!--             {% if session.username %}
            <form id = "edit_people{{result.project.pid}}" style="display: none" method="post" enctype="mulitpart/form-data">
                <input type="hidden" name=pid value = "{{result.project.pid}}">
                <input type="hidden" name="people_name" value="{{people.name}}">
                <input type="submit" value="Delete">
            </form>
            {% endif %} -->
            {% endfor %}
        </p>
        {% endif %}
    <p></p>
     {% if session.username %}
        <button onclick="myFunction('edit_people{{result.project.pid}}')"> REMOVE People </button>
        <form id = "edit_people{{result.project.pid}}" style="display: none" method="post" enctype="mulitpart/form-data">
        <input type="hidden" name="op_people" value="delete">
        <input type="hidden" name="pid" value="{{result.project.pid}}">
        {% for people in result.peoples %}
            <input type="radio" name="people_name" value="{{people.name}}"> {{people.name}} <br>
        {% endfor %}
        <input type="submit" value = "Delete">
        </form>
        <br>
        <br>
        <form method="post" enctype="mulitpart/form-data">
            <input type="hidden" name="op_people" value="add">
            <input type="hidden" name="pid" value="{{result.project.pid}}">
            <strong>Add People here:</strong>
            <br>
            Please enter people name here: <input type="text" name="people_name">
            <br>
            Please enter his/her website here: <input type="text" name="people_website">
            <br>
            <input type="submit" value="Submit">
        </form>
        <br>
        <br>
        <br>
    {% endif %}


    {% if result['project']['picid'] %}
    <img src="/static/images/{{result['project']['picid']}}", alt ="{{result['project']['picid']}}", width="20%">
    {% endif %}
    <p></p>
    <p>
        {{result.project.contents}}
    </p>
    {% if session.username %}
    <br>
    <button onclick="myFunction('edit_content{{result.project.pid}}')"> Edit Project content </button>
    <form id = "edit_content{{result.project.pid}}" style="display: none" method="post" enctype="mulitpart/form-data">
        <!-- <input type=text height="50" name=pjcontent placeholder="Please edit the content here!" size = 200 height="20"> <br> -->
        <textarea warp ="soft" rows = "15" cols="150" name="pjcontent" placeholder="Please edit the content here!"></textarea>
        <!-- <textarea class="input" rows = "15" cols="150" name="pjcontent"></textarea> -->
        <input type="hidden" name=pid value = "{{result.project.pid}}"> <br>       
        <input type="submit" value="Submit">
    </form>
    {% endif %}
    <br>
    <br>
    {% for new in result.news %}
    <p>
        <font color="red">
                        <b>{{new.title}}  </b>
                                            </font>
        <br>
        "{{new.newscontent}}"
    {% if session.username %}
    <br>
    <form method="post" enctype="mulitpart/form-data" align="right">
        <input type="hidden" name="op_news" value="delete">
        <input type="hidden" name="new_id" value="{{new.newid}}">
        <input type="submit" value="Delete">
    </form>
    {% endif %}
    </p>
    {% endfor %}
    {% if session.username %}
    <br>
    <button onclick="myFunction('add_news{{result.project.pid}}')"> Add more news </button>
    <form id = "add_news{{result.project.pid}}" style="display: none" method="post" enctype="mulitpart/form-data">
        <input type="hidden" name="op_news" value="add">
        <input type="hidden" name="pid" value="{{result.project.pid}}">
        Please enter the title of the News: <input type="text" name="news_title" size="80">
        <br>
        <textarea warp ="soft" rows = "5" cols="150" name="newscontent" placeholder="News content here!"></textarea>
        <br>
        <input type="submit" value="Submit">
    </form>
    {% endif %}
    <br>
    <p>
        <b>
            <font size="3" face="Arial">Publications:</font>
        </b><br>
    </p>
    <ul>
        {% for publication in result.publications %}
        <li>
            {{publication.artist}} <a href ="{{publication.link}}">{{publication.title}}</a>
            <i>
                {{publication.background}}
            </i>
            {% for public in publication.public_content %}
            <br>
            <a href="{{public.link}}">
                <font color="#04B404"><strong>{{public.title}}</strong></font>
            </a>
            {% endfor %}
            {% if session.username %}
            <form method="post" enctype="mulitpart/form-data" align="right">
                <input type="hidden" name="op_public" value="delete">
                <input type="hidden" name="public_id" value="{{publication.publicid}}">
                <input type="submit" value="Delete">
            </form>
            {% endif %}
        </li>
        {% endfor %}
    </ul>
    {% if session.username %}
    <br>
    <br>
    <button onclick="myFunction('add_public{{result.project.pid}}')"> Add more publications </button>
    <form id = "add_public{{result.project.pid}}" style="display: none" method="post" enctype="mulitpart/form-data">
        <input type="hidden" name="op_public" value="add">
        <input type="hidden" name="pid" value="{{result.project.pid}}">
        Please enter title of the publication: <input type="text" name="public_title" size="100">
        <br>
        Please enter the link to the publication: <input type="text" name="link" size="100">
        <br>
        Please enter the reference of the publication: <input type="text" name="background" size="100">
        <br>
        Please enter the artists of the publication: <input type="text" name="artist" size = "100">
        <br>
        <input type="submit" value="Submit">
    </form>
    {% endif %}
    <br> 
    <br>
    {% endfor %}
</body>

<script>
    function myFunction(y) {
        var x = document.getElementById(y);
        if(x.style.display === 'none'){
            x.style.display = 'block';
        }
        else   {
            x.style.display ='none';
        }
    }
</script>

<footer>
	<p>Done by WEILUN SHI</p>
</footer>
</html>
{% endblock %}

Barzan's website/templates/login.html
{% extends "base.html" %} {% block content %}

<head>
  <title>Login</title>
  <meta charset="UTF-8">
  <meta name="description" content="BARZAN MOZAFARI's website">
</head>

<body>
<div class = "center">
	<h1>
		Login!
	</h1>
	<p>
		Hello! you can login here!
	</p>
	{% for err in errList %}
	<p class="error">
		{{err}}
	</p>
	{% endfor %}
	<form action="" method="post" enctype="mulitpart/form-data">
	Please enter your username: <input type="text" name="username", id="login_username_input"> <br>
	Please enter your password: <input type="password" name="password", id="login_password_input"> <br>
	<input type="submit" value="Login" id="login_submit">
	</form>
	</div>
</body>

{% endblock %}

Barzan's website/templates/project_edit.html
{% extends "base.html" %}
{% block content %}
<html>
<head>
	<title>
		BARZAN MOZAFARI's project edit
	</title>
	<meta charset="UTF-8">
	<meta name = "description" content="BARZAN MOZAFARI's project">
</head>
<body>
<h1>New Projects</h1>
	{% for err in errList %}
		<p class="error">
			{{err}}
		</p>
	{% endfor %}
	<table>
		<form action="" method="post" enctype=multipart/form-data>
		
		<tr>
			<td>Project name:</td>
			<td><input type = 'text' size="80" name = 'project_name' id = project_name></td>
		</tr>
		
		<tr>
			<td>Subtitle name:</td>
			<td><input type = 'text' size="80" name = 'project_subtitle' id = project_subtitle></td>
		</tr>

		<tr>
			<td>Contents:</td>
			<td><textarea warp ="soft" rows = "15" cols="150" name="project_contents" placeholder="Please edit the content here!"></textarea></td>
		</tr>
		<tr>
			<td>Project website:</td>
			<td><input type = 'text' size="50" name = 'project_website' id = project_website></td>
		</tr>
		<tr>
			<td>Project image:</td>
			<td><input type=file name=file></td>
		</tr>
		<tr>
			<td>Status:</td>
			<td>
				<input type = 'radio' name = 'status' value="current"> current
				<br>
				<input type="radio" name="status" value="past"> past
				<br>
			</td>
		</tr>
		<tr>
			<input type="submit" value="Submit">
		</tr>
		</form>
	</table>
</body>
{% endblock %}
<footer>
	<p>Done by WEILUN SHI</p>
</footer>
</html>


Barzan's website/templates/user_edit.html
{% extends "base.html" %} {% block content %}

<head>
  <title>User</title>
  <meta charset="UTF-8">
  <meta name="description" content="EECS485 P1 Albums Page">
</head>

<body>
<div class = "center">
	<h1>
		Edit Account!!
	</h1>
	<p>
		Hello! you can edit your info here!
	</p>
	{% for err in errList %}
	<p class="error">
		{{err}}
	</p>
	{% endfor %}

	<form action="" method="post" enctype="multipart/form-data">
		<p>
			FirstName: <input type="text" name="firstname", id="update_firstname_input">
		</p>
		<p>
			<input type="submit" value="Submit" id="update_firstname_submit">
		</p>
	</form>
	<form action="" method="post" enctype="multipart/form-data">
		<p>
			LastName: <input type="text" name="lastname", id="update_lastname_input">
		</p>
		<p>
			<input type="submit" value="Submit" id="update_lasname_submit">
		</p>
	</form>
	<form action="" method="post" enctype="multipart/form-data">
		<p>
			Password1: <input type=password name="password1", id="update_password1_input">
		</p>
		<p>
			Password2: <input type=password name="password2", id="update_password2_input">
		</p>
		<p>
			<input type="submit" value="Submit" id="update_password_submit">
		</p>
	</form>
</div>
</body>
{% endblock %}